Repository milieuinfo/vl-mapactions, pull requests merged in 2021-02, with the labels that each got.

#41 Voeg OpenLayers OlGML2, OlGML3, OlGML32 exports toe (#40)
  src/vl-mapactions-all.js
Labels: chore

#42 Na het verwijderen van een feature via een box selectie interactie moet de kaart opnieuw renderen
  dist/vl-mapactions.js
  src/vl-mapactions-delete-action.js
  test/unit/vl-mapactions-delete-action.test.js
Labels: bug

#44 Rekening houden met features zonder id bij verwijderen interactie
  dist/vl-mapactions.js
  src/vl-mapactions-delete-action.js
  test/unit/vl-mapactions-delete-action.test.js
Labels: bug

#45 Verbetering stijl teken en select acties
  dist/style.css
  dist/vl-mapactions.js
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-mapactions-box-select-action.js
  src/vl-mapactions-delete-action.js
  src/vl-mapactions-draw-action.js
  test/unit/vl-mapactions-delete-action.test.js
Labels: enhancement

#47 Build zal variabelen niet meer hernoemen zodat instanceof functionaliteit werkt
  dist/vl-mapactions.js
  package.json
  test/unit/vl-mapactions.test.js
  webpack.config.js
Labels: bug
